site_name: Just document it

# Navigation menu
# nav:
#   - Home: index.md
#   - Parent:
#     - Arch Linux: ArchLinux/archy.md
#         - Helper: user-story/commands.md

nav:
  - Home: index.md
  - Arch Linux: 
    - ArchLinux/archy.md
    - Helper: user-story/commands.md

# Theme
theme:
    features:
      - tabs
      - navigation.indexes
    name: material
    icon:
      logo: material/cloud
    font:
      text: Ubuntu
      code: Ubuntu Mono
    static_templates:
      - 404.html

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
#  - pymdownx.magiclink:
#      repo_url_shorthand: true
#      user: squidfunk
#      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime

copyright: Copyright &copy; 2023 Daniel Nikoloski
